/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LupaSandiRouteImport } from './routes/lupa-sandi'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppKeuanganRouteImport } from './routes/_app/keuangan'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ResetSandiTokenRouteImport } from './routes/reset-sandi.$token'
import { Route as AppEventsEventIdRouteImport } from './routes/_app/events.$eventId'
import { Route as AppEventsNewRouteImport } from './routes/_app/events.new'
import { Route as AppPesananIndexRouteImport } from './routes/_app/pesanan/index'
import { Route as AppPesananNewRouteImport } from './routes/_app/pesanan/new'
import { Route as AppProfilIndexRouteImport } from './routes/_app/profil/index'
import { Route as AppProfilLanggananRouteImport } from './routes/_app/profil/langganan'
import { Route as TagihanEventIdOrderIdRouteImport } from './routes/tagihan.$eventId.$orderId'
import { Route as AppInvoiceEventIdOrderIdRouteImport } from './routes/_app/invoice.$eventId.$orderId'
import { Route as AppProfilCustomersIndexRouteImport } from './routes/_app/profil/customers/index'
import { Route as AppProfilFeeRulesIndexRouteImport } from './routes/_app/profil/fee-rules/index'
import { Route as AppProfilFeeRulesFeeRuleIdRouteImport } from './routes/_app/profil/fee-rules/$feeRuleId'
import { Route as AppProfilFeeRulesNewRouteImport } from './routes/_app/profil/fee-rules/new'
import { Route as ApiAuthGoogleIndexRouteImport } from './routes/api/auth/google/index'
import { Route as ApiAuthGoogleCallbackRouteImport } from './routes/api/auth/google/callback'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LupaSandiRoute = LupaSandiRouteImport.update({
  id: '/lupa-sandi',
  path: '/lupa-sandi',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppKeuanganRoute = AppKeuanganRouteImport.update({
  id: '/keuangan',
  path: '/keuangan',
  getParentRoute: () => AppRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ResetSandiTokenRoute = ResetSandiTokenRouteImport.update({
  id: '/reset-sandi/$token',
  path: '/reset-sandi/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppEventsEventIdRoute = AppEventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => AppRoute,
} as any)
const AppEventsNewRoute = AppEventsNewRouteImport.update({
  id: '/events/new',
  path: '/events/new',
  getParentRoute: () => AppRoute,
} as any)
const AppPesananIndexRoute = AppPesananIndexRouteImport.update({
  id: '/pesanan/',
  path: '/pesanan/',
  getParentRoute: () => AppRoute,
} as any)
const AppPesananNewRoute = AppPesananNewRouteImport.update({
  id: '/pesanan/new',
  path: '/pesanan/new',
  getParentRoute: () => AppRoute,
} as any)
const AppProfilIndexRoute = AppProfilIndexRouteImport.update({
  id: '/profil/',
  path: '/profil/',
  getParentRoute: () => AppRoute,
} as any)
const AppProfilLanggananRoute = AppProfilLanggananRouteImport.update({
  id: '/profil/langganan',
  path: '/profil/langganan',
  getParentRoute: () => AppRoute,
} as any)
const TagihanEventIdOrderIdRoute = TagihanEventIdOrderIdRouteImport.update({
  id: '/tagihan/$eventId/$orderId',
  path: '/tagihan/$eventId/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppInvoiceEventIdOrderIdRoute =
  AppInvoiceEventIdOrderIdRouteImport.update({
    id: '/invoice/$eventId/$orderId',
    path: '/invoice/$eventId/$orderId',
    getParentRoute: () => AppRoute,
  } as any)
const AppProfilCustomersIndexRoute = AppProfilCustomersIndexRouteImport.update({
  id: '/profil/customers/',
  path: '/profil/customers/',
  getParentRoute: () => AppRoute,
} as any)
const AppProfilFeeRulesIndexRoute = AppProfilFeeRulesIndexRouteImport.update({
  id: '/profil/fee-rules/',
  path: '/profil/fee-rules/',
  getParentRoute: () => AppRoute,
} as any)
const AppProfilFeeRulesFeeRuleIdRoute =
  AppProfilFeeRulesFeeRuleIdRouteImport.update({
    id: '/profil/fee-rules/$feeRuleId',
    path: '/profil/fee-rules/$feeRuleId',
    getParentRoute: () => AppRoute,
  } as any)
const AppProfilFeeRulesNewRoute = AppProfilFeeRulesNewRouteImport.update({
  id: '/profil/fee-rules/new',
  path: '/profil/fee-rules/new',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthGoogleIndexRoute = ApiAuthGoogleIndexRouteImport.update({
  id: '/api/auth/google/',
  path: '/api/auth/google/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthGoogleCallbackRoute = ApiAuthGoogleCallbackRouteImport.update({
  id: '/api/auth/google/callback',
  path: '/api/auth/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/lupa-sandi': typeof LupaSandiRoute
  '/register': typeof RegisterRoute
  '/keuangan': typeof AppKeuanganRoute
  '/reset-sandi/$token': typeof ResetSandiTokenRoute
  '/admin/': typeof AdminIndexRoute
  '/events/$eventId': typeof AppEventsEventIdRoute
  '/events/new': typeof AppEventsNewRoute
  '/pesanan/new': typeof AppPesananNewRoute
  '/profil/langganan': typeof AppProfilLanggananRoute
  '/tagihan/$eventId/$orderId': typeof TagihanEventIdOrderIdRoute
  '/pesanan/': typeof AppPesananIndexRoute
  '/profil/': typeof AppProfilIndexRoute
  '/invoice/$eventId/$orderId': typeof AppInvoiceEventIdOrderIdRoute
  '/profil/fee-rules/$feeRuleId': typeof AppProfilFeeRulesFeeRuleIdRoute
  '/profil/fee-rules/new': typeof AppProfilFeeRulesNewRoute
  '/api/auth/google/callback': typeof ApiAuthGoogleCallbackRoute
  '/profil/customers/': typeof AppProfilCustomersIndexRoute
  '/profil/fee-rules/': typeof AppProfilFeeRulesIndexRoute
  '/api/auth/google/': typeof ApiAuthGoogleIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/lupa-sandi': typeof LupaSandiRoute
  '/register': typeof RegisterRoute
  '/keuangan': typeof AppKeuanganRoute
  '/reset-sandi/$token': typeof ResetSandiTokenRoute
  '/': typeof AppIndexRoute
  '/admin': typeof AdminIndexRoute
  '/events/$eventId': typeof AppEventsEventIdRoute
  '/events/new': typeof AppEventsNewRoute
  '/pesanan/new': typeof AppPesananNewRoute
  '/profil/langganan': typeof AppProfilLanggananRoute
  '/tagihan/$eventId/$orderId': typeof TagihanEventIdOrderIdRoute
  '/pesanan': typeof AppPesananIndexRoute
  '/profil': typeof AppProfilIndexRoute
  '/invoice/$eventId/$orderId': typeof AppInvoiceEventIdOrderIdRoute
  '/profil/fee-rules/$feeRuleId': typeof AppProfilFeeRulesFeeRuleIdRoute
  '/profil/fee-rules/new': typeof AppProfilFeeRulesNewRoute
  '/api/auth/google/callback': typeof ApiAuthGoogleCallbackRoute
  '/profil/customers': typeof AppProfilCustomersIndexRoute
  '/profil/fee-rules': typeof AppProfilFeeRulesIndexRoute
  '/api/auth/google': typeof ApiAuthGoogleIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/lupa-sandi': typeof LupaSandiRoute
  '/register': typeof RegisterRoute
  '/_app/keuangan': typeof AppKeuanganRoute
  '/reset-sandi/$token': typeof ResetSandiTokenRoute
  '/_app/': typeof AppIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/_app/events/$eventId': typeof AppEventsEventIdRoute
  '/_app/events/new': typeof AppEventsNewRoute
  '/_app/pesanan/new': typeof AppPesananNewRoute
  '/_app/profil/langganan': typeof AppProfilLanggananRoute
  '/tagihan/$eventId/$orderId': typeof TagihanEventIdOrderIdRoute
  '/_app/pesanan/': typeof AppPesananIndexRoute
  '/_app/profil/': typeof AppProfilIndexRoute
  '/_app/invoice/$eventId/$orderId': typeof AppInvoiceEventIdOrderIdRoute
  '/_app/profil/fee-rules/$feeRuleId': typeof AppProfilFeeRulesFeeRuleIdRoute
  '/_app/profil/fee-rules/new': typeof AppProfilFeeRulesNewRoute
  '/api/auth/google/callback': typeof ApiAuthGoogleCallbackRoute
  '/_app/profil/customers/': typeof AppProfilCustomersIndexRoute
  '/_app/profil/fee-rules/': typeof AppProfilFeeRulesIndexRoute
  '/api/auth/google/': typeof ApiAuthGoogleIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/lupa-sandi'
    | '/register'
    | '/keuangan'
    | '/reset-sandi/$token'
    | '/admin/'
    | '/events/$eventId'
    | '/events/new'
    | '/pesanan/new'
    | '/profil/langganan'
    | '/tagihan/$eventId/$orderId'
    | '/pesanan/'
    | '/profil/'
    | '/invoice/$eventId/$orderId'
    | '/profil/fee-rules/$feeRuleId'
    | '/profil/fee-rules/new'
    | '/api/auth/google/callback'
    | '/profil/customers/'
    | '/profil/fee-rules/'
    | '/api/auth/google/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/lupa-sandi'
    | '/register'
    | '/keuangan'
    | '/reset-sandi/$token'
    | '/'
    | '/admin'
    | '/events/$eventId'
    | '/events/new'
    | '/pesanan/new'
    | '/profil/langganan'
    | '/tagihan/$eventId/$orderId'
    | '/pesanan'
    | '/profil'
    | '/invoice/$eventId/$orderId'
    | '/profil/fee-rules/$feeRuleId'
    | '/profil/fee-rules/new'
    | '/api/auth/google/callback'
    | '/profil/customers'
    | '/profil/fee-rules'
    | '/api/auth/google'
  id:
    | '__root__'
    | '/_app'
    | '/admin'
    | '/login'
    | '/lupa-sandi'
    | '/register'
    | '/_app/keuangan'
    | '/reset-sandi/$token'
    | '/_app/'
    | '/admin/'
    | '/_app/events/$eventId'
    | '/_app/events/new'
    | '/_app/pesanan/new'
    | '/_app/profil/langganan'
    | '/tagihan/$eventId/$orderId'
    | '/_app/pesanan/'
    | '/_app/profil/'
    | '/_app/invoice/$eventId/$orderId'
    | '/_app/profil/fee-rules/$feeRuleId'
    | '/_app/profil/fee-rules/new'
    | '/api/auth/google/callback'
    | '/_app/profil/customers/'
    | '/_app/profil/fee-rules/'
    | '/api/auth/google/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  LupaSandiRoute: typeof LupaSandiRoute
  RegisterRoute: typeof RegisterRoute
  ResetSandiTokenRoute: typeof ResetSandiTokenRoute
  TagihanEventIdOrderIdRoute: typeof TagihanEventIdOrderIdRoute
  ApiAuthGoogleCallbackRoute: typeof ApiAuthGoogleCallbackRoute
  ApiAuthGoogleIndexRoute: typeof ApiAuthGoogleIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lupa-sandi': {
      id: '/lupa-sandi'
      path: '/lupa-sandi'
      fullPath: '/lupa-sandi'
      preLoaderRoute: typeof LupaSandiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/keuangan': {
      id: '/_app/keuangan'
      path: '/keuangan'
      fullPath: '/keuangan'
      preLoaderRoute: typeof AppKeuanganRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/reset-sandi/$token': {
      id: '/reset-sandi/$token'
      path: '/reset-sandi/$token'
      fullPath: '/reset-sandi/$token'
      preLoaderRoute: typeof ResetSandiTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/events/$eventId': {
      id: '/_app/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof AppEventsEventIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/events/new': {
      id: '/_app/events/new'
      path: '/events/new'
      fullPath: '/events/new'
      preLoaderRoute: typeof AppEventsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pesanan/': {
      id: '/_app/pesanan/'
      path: '/pesanan'
      fullPath: '/pesanan/'
      preLoaderRoute: typeof AppPesananIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pesanan/new': {
      id: '/_app/pesanan/new'
      path: '/pesanan/new'
      fullPath: '/pesanan/new'
      preLoaderRoute: typeof AppPesananNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profil/': {
      id: '/_app/profil/'
      path: '/profil'
      fullPath: '/profil/'
      preLoaderRoute: typeof AppProfilIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profil/langganan': {
      id: '/_app/profil/langganan'
      path: '/profil/langganan'
      fullPath: '/profil/langganan'
      preLoaderRoute: typeof AppProfilLanggananRouteImport
      parentRoute: typeof AppRoute
    }
    '/tagihan/$eventId/$orderId': {
      id: '/tagihan/$eventId/$orderId'
      path: '/tagihan/$eventId/$orderId'
      fullPath: '/tagihan/$eventId/$orderId'
      preLoaderRoute: typeof TagihanEventIdOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/invoice/$eventId/$orderId': {
      id: '/_app/invoice/$eventId/$orderId'
      path: '/invoice/$eventId/$orderId'
      fullPath: '/invoice/$eventId/$orderId'
      preLoaderRoute: typeof AppInvoiceEventIdOrderIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profil/customers/': {
      id: '/_app/profil/customers/'
      path: '/profil/customers'
      fullPath: '/profil/customers/'
      preLoaderRoute: typeof AppProfilCustomersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profil/fee-rules/': {
      id: '/_app/profil/fee-rules/'
      path: '/profil/fee-rules'
      fullPath: '/profil/fee-rules/'
      preLoaderRoute: typeof AppProfilFeeRulesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profil/fee-rules/$feeRuleId': {
      id: '/_app/profil/fee-rules/$feeRuleId'
      path: '/profil/fee-rules/$feeRuleId'
      fullPath: '/profil/fee-rules/$feeRuleId'
      preLoaderRoute: typeof AppProfilFeeRulesFeeRuleIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profil/fee-rules/new': {
      id: '/_app/profil/fee-rules/new'
      path: '/profil/fee-rules/new'
      fullPath: '/profil/fee-rules/new'
      preLoaderRoute: typeof AppProfilFeeRulesNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/google/': {
      id: '/api/auth/google/'
      path: '/api/auth/google'
      fullPath: '/api/auth/google/'
      preLoaderRoute: typeof ApiAuthGoogleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/google/callback': {
      id: '/api/auth/google/callback'
      path: '/api/auth/google/callback'
      fullPath: '/api/auth/google/callback'
      preLoaderRoute: typeof ApiAuthGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppKeuanganRoute: typeof AppKeuanganRoute
  AppIndexRoute: typeof AppIndexRoute
  AppEventsEventIdRoute: typeof AppEventsEventIdRoute
  AppEventsNewRoute: typeof AppEventsNewRoute
  AppPesananNewRoute: typeof AppPesananNewRoute
  AppProfilLanggananRoute: typeof AppProfilLanggananRoute
  AppPesananIndexRoute: typeof AppPesananIndexRoute
  AppProfilIndexRoute: typeof AppProfilIndexRoute
  AppInvoiceEventIdOrderIdRoute: typeof AppInvoiceEventIdOrderIdRoute
  AppProfilFeeRulesFeeRuleIdRoute: typeof AppProfilFeeRulesFeeRuleIdRoute
  AppProfilFeeRulesNewRoute: typeof AppProfilFeeRulesNewRoute
  AppProfilCustomersIndexRoute: typeof AppProfilCustomersIndexRoute
  AppProfilFeeRulesIndexRoute: typeof AppProfilFeeRulesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppKeuanganRoute: AppKeuanganRoute,
  AppIndexRoute: AppIndexRoute,
  AppEventsEventIdRoute: AppEventsEventIdRoute,
  AppEventsNewRoute: AppEventsNewRoute,
  AppPesananNewRoute: AppPesananNewRoute,
  AppProfilLanggananRoute: AppProfilLanggananRoute,
  AppPesananIndexRoute: AppPesananIndexRoute,
  AppProfilIndexRoute: AppProfilIndexRoute,
  AppInvoiceEventIdOrderIdRoute: AppInvoiceEventIdOrderIdRoute,
  AppProfilFeeRulesFeeRuleIdRoute: AppProfilFeeRulesFeeRuleIdRoute,
  AppProfilFeeRulesNewRoute: AppProfilFeeRulesNewRoute,
  AppProfilCustomersIndexRoute: AppProfilCustomersIndexRoute,
  AppProfilFeeRulesIndexRoute: AppProfilFeeRulesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  LupaSandiRoute: LupaSandiRoute,
  RegisterRoute: RegisterRoute,
  ResetSandiTokenRoute: ResetSandiTokenRoute,
  TagihanEventIdOrderIdRoute: TagihanEventIdOrderIdRoute,
  ApiAuthGoogleCallbackRoute: ApiAuthGoogleCallbackRoute,
  ApiAuthGoogleIndexRoute: ApiAuthGoogleIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
